define([
        'backbone',
        'hbs/handlebars',
        'text!./icons.hbs'
    ],
    function(Backbone, Handlebars, templateString) {
        'use strict';
        //Here is how to generate this list.
        //wget https://github.intuit.com/raw/SBG/harmony-ui-components/develop/src/styles/icons/css/harmony.css
        //cat h.css | grep 'hi-' |sed 's/:before {/',/g'| sed 's/.hi-/'hi-/g' |sort
        var model = [
            'hi-accountant',
            'hi-accountant-tool',
            'hi-add-user',
            'hi-adjust',
            'hi-anniversary',
            'hi-announce',
            'hi-appointment',
            'hi-apps',
            'hi-arrange',
            'hi-attach',
            'hi-audio',
            'hi-bank',
            'hi-birthday',
            'hi-bookmark',
            'hi-calendar',
            'hi-camera',
            'hi-cancel',
            'hi-cash',
            'hi-chat',
            'hi-chat-o',
            'hi-check-o',
            'hi-checklist',
            'hi-checkmark',
            'hi-checks',
            'hi-chevron-down',
            'hi-chevron-left',
            'hi-chevron-right',
            'hi-chevron-up',
            'hi-circle-alert',
            'hi-circle-check',
            'hi-circle-info',
            'hi-close',
            'hi-close',
            'hi-copy',
            'hi-create',
            'hi-create-lg',
            'hi-credit-card',
            'hi-customers',
            'hi-customize',
            'hi-dashboard',
            'hi-delete',
            'hi-direct-deposit',
            'hi-document',
            'hi-document-alt',
            'hi-download',
            'hi-draft',
            'hi-drag',
            'hi-duplicate',
            'hi-edit',
            'hi-email',
            'hi-employees',
            'hi-expenses',
            'hi-expert',
            'hi-export',
            'hi-filter',
            'hi-flag',
            'hi-folder',
            'hi-headset',
            'hi-help',
            'hi-help-o',
            'hi-history',
            'hi-history',
            'hi-image',
            'hi-import',
            'hi-inventory',
            'hi-invoices',
            'hi-labs',
            'hi-lightbulb-o',
            'hi-list',
            'hi-lock',
            'hi-mailbox',
            'hi-map',
            'hi-map-pin',
            'hi-marketing',
            'hi-marketing-alt',
            'hi-maximize',
            'hi-message',
            'hi-microphone',
            'hi-mileage',
            'hi-minimize',
            'hi-new-window',
            'hi-newsletter',
            'hi-no-access',
            'hi-note',
            'hi-offline',
            'hi-payments',
            'hi-phone',
            'hi-pin',
            'hi-play',
            'hi-pop-in',
            'hi-pop-out',
            'hi-preview',
            'hi-print',
            'hi-pro-advisor',
            'hi-products',
            'hi-receipt-o',
            'hi-receipts',
            'hi-reconcile',
            'hi-refresh',
            'hi-reports',
            'hi-save',
            'hi-schedule',
            'hi-search',
            'hi-send',
            'hi-settings',
            'hi-settings-o',
            'hi-share',
            'hi-speech-bubble',
            'hi-star',
            'hi-star-o',
            'hi-survey',
            'hi-swap',
            'hi-tag',
            'hi-taxes',
            'hi-tear-alert-lt',
            'hi-tear-alert-rt',
            'hi-tear-check-lt',
            'hi-tear-check-rt',
            'hi-tear-pending',
            'hi-thumb-down',
            'hi-thumb-up',
            'hi-transactions',
            'hi-unlink',
            'hi-unlock',
            'hi-upgrade',
            'hi-upload',
            'hi-user',
            'hi-vendors',
            'hi-circle-alert',
            'hi-circle-check',
            'hi-circle-info',
            'hi-arrange',
            'hi-drag'
        ],
            i,
            icon,
            template,
            TypographyDemoView = Backbone.View.extend({

                render: function() {
                    var mo = [];
                    for (i = 0; i < model.length; i++) {
                        icon = {};
                        icon.name = model[i].replace('hi-', '').replace('hi-icon-', '').replace('-alt', ' alternate').replace('-o', ' alternate').replace('-rt', ' right').replace('-lt',
                            'left').replace('-', ' ');
                        icon.class = model[i];
                        mo.push(icon);
                    }

                    template = Handlebars.compile(templateString);
                    this.$el.html(template({
                        'icons': mo
                    }));
                    return this;
                }
            });

        return TypographyDemoView;
    }
);
